#include "about.h"
#include "../GRRLIB/GRRLIB.h"
#include "../res/res.h"
#include "../res/strings.h"
#include "../ui.h"

void ABOUT_render() {
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_1_Y, STR_ABOUT, FONTSIZE_SMALL, TEXT_COLOR_PRIMARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_2_Y, STR_ABOUT_1, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_3_Y, STR_ABOUT_2, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_4_Y, STR_ABOUT_3, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_5_Y, STR_ABOUT_4, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_6_Y, STR_ABOUT_5, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_7_Y, STR_ABOUT_6, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_8_Y, STR_ABOUT_7, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
  GRRLIB_DrawText(UI_LINE_X, UI_LINE_9_Y, STR_ABOUT_8, FONTSIZE_SMALL, TEXT_COLOR_SECONDARY);
}
